spring:
  data:
    mongodb:
      uri: mongodb+srv://aqib_mustafa:aqib_password@cluster0.epbqm.mongodb.net/Hospital?retryWrites=true&w=majority

server:
  port: 8092

graphql:
  servlet:
    maxQueryDepth: 100
